# file_name = r'U:\test_python\username2.csv'
# Windows path work well without having to escpae with 'r': raw
file_name = 'username.csv'
# file_name2='username2.csv'
delimiter = ','
log_file = 'log.txt'
# folder_to_zip=r'U:\0_cc-pj-con'
folder_to_zip=r'C:\Users\Angel\Desktop\python_workspace\python_jupyNotebooks'
# path_to_zip_file=r'U:\directory.zip'
path_to_credentials_module='credentials_module.json'
